@origin = http://localhost:3313
@basePath = /api/portfolio/688dfee6991af7c0147ca905/assetrecord

###
# Get all asset records for portfolio
GET {{origin}}{{basePath}}
Content-Type: application/json

###
# Get specific asset record
GET {{origin}}{{basePath}}/688dfee6991af7c0147ca905
Content-Type: application/json

###
# Create new portfolio asset record
POST {{origin}}{{basePath}}
Content-Type: application/json

{
    "_assetId": "688dfb7e991af7c0147ca7c3",
    "date": "2025-01-10",
    "change": 100,
    "result": 0,
    "price": 0,
    "unit": "KRW",
    "memo": "Sample"
}

###
# Update portfolio asset record
PUT {{origin}}{{basePath}}/688e059db3baf04739a765f4
Content-Type: application/json

{
  "_assetId": "688dfb7e991af7c0147ca7c3",
  "date": "2025-01-10",
  "change": 120,
  "result": 0,
  "price": 0,
  "unit": "KRW",
  "memo": "Updated portfolio entry"
}

###
# Delete portfolio asset record
DELETE {{origin}}{{basePath}}/688e04a5991af7c0147caba2
Content-Type: application/json